// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJwZn900HLfb9SuurfOewGgqZPXMAup8Y',
    appId: '1:631008849296:web:bf44a8f5d4c8d7a7ef5715',
    messagingSenderId: '631008849296',
    projectId: 'project-hell-750ea',
    authDomain: 'project-hell-750ea.firebaseapp.com',
    storageBucket: 'project-hell-750ea.firebasestorage.app',
    measurementId: 'G-X5H7HRQXQ7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdtfbXhhVc64tl6NtFuORSKrNkSb-LjU',
    appId: '1:631008849296:ios:73aded4667616f69ef5715',
    messagingSenderId: '631008849296',
    projectId: 'project-hell-750ea',
    storageBucket: 'project-hell-750ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBdtfbXhhVc64tl6NtFuORSKrNkSb-LjU',
    appId: '1:631008849296:ios:73aded4667616f69ef5715',
    messagingSenderId: '631008849296',
    projectId: 'project-hell-750ea',
    storageBucket: 'project-hell-750ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJwZn900HLfb9SuurfOewGgqZPXMAup8Y',
    appId: '1:631008849296:web:bf44a8f5d4c8d7a7ef5715',
    messagingSenderId: '631008849296',
    projectId: 'project-hell-750ea',
    authDomain: 'project-hell-750ea.firebaseapp.com',
    storageBucket: 'project-hell-750ea.firebasestorage.app',
    measurementId: 'G-X5H7HRQXQ7',
  );
}